destination = {
    # 'beijing': 'bjs',
    # 'shanghai': 'sha',
    'guangzhou': 'can',
    # 'hongkong': 'hkg',
    # 'hangzhou': 'hgh',
    # 'xiamen': 'xmn',
    # 'nanjing': 'nkg',
    # 'macau': 'mfm',
    # 'chengdu': 'ctu',
    # 'qingdao': 'tao',
    # 'taipei': 'tpe',
    # 'fuzhou': 'foc',
    # 'tianjin': 'tsn',
    # 'shenzhen': 'szx',
    # 'dalian': 'dlc',
    # 'shenyang': 'she',
    # 'kunming': 'kmg',
    # 'wuhan': 'wuh',
    # 'ningbo': 'ngb',
    # 'wuxi': 'wux',
    # 'jinjiang': 'jjn',
    # 'chongqing': 'ckg',
    # 'sanya': 'syx',
    # 'xian': 'sia',
}

international = {
    # 'seoul': 'sel',
    # 'tokyo': 'tyo',
    # 'singapore': 'sin',
    # 'bangkok': 'bkk',
    # 'osaka': 'osa',
    # 'hochiminhcity': 'sgn',
    # 'manila': 'mnl',
    # 'nagoya': 'ngo',
    # 'london': 'lon',
    # 'kualalumpur': 'kul',
    # 'pusan': 'pus',
    # 'sydney': 'syd',
    # 'frankfurt': 'fra',
    # 'vancouver': 'yvr',
    # 'paris': 'par',
    # 'newyork': 'nyc',
    'losangeles': 'lax',
    # 'honolulu': 'hnl',
    # 'bali': 'dps',
    # 'moscow': 'mow'
}
